---
permalink: pretty
markdown: kramdown
exclude:
  - Gem*
  - "*.lock"
  - "*rb"
  - ".git*"
  - "*.md"
  - "*.json"
  - node_modules
  - vendor
  - gulp*
  - ".jekyll-metadata"
  - ".*"
timezone: UTC
author: Nerdlab
title: "CityHacks 2018"
description: "Hoe kan de Stad zorgen voor een betere leefomgeving voor haar inwoners. Bedenk een app die steunt op open data en toon aan hoe deze mensen zal helpen. Dat kan een app voor het web, je telefoon of een nieuw uitgevonden toestel zijn."
url: "https://cityhacks.be"
navigation:
  - title: Opdracht
    url: "index.html#opdracht"
  - title: Programma
    url: "index.html#programma"
  - title: Open data
    url: "index.html#data"
navigation-cta:
  - title: De resultaten
    url: "index.html#inschrijven"

social:
  twitter_username: nerdlab9000
  instagram_username: nerdlab9000
legal:
  year: '2018'
  company: 'Nerdlab vzw'
  email: 'info@nerdlab.be'
  address: 'Ma√Øsstraat 181'
  city: '9000 Ghent'
  phone: '+32 486 22 72 02'
  btw: 'BE 0562.981.862'
labels:
  legal: Kleine lettertjes
collections:
  pages:
    title: Pages
    output: true
defaults:
- scope:
    path: ""
    type: pages
  values:
    is_page: true
